### ISSUE TITLE
Code background and color should be defined by Highlight theme

### ISSUE THREAD

**Issue by borisschapira** [hakimel/reveal.js#1114] opened 2015-01-25 10:15 UTC
https://github.com/hakimel/reveal.js/blob/master/css/theme/template/theme.scss#L181

these lines are incompatible with several hljs themes like mono-blue ou github...

Is there a reason for these lines ? Could we remove them ?

**Comment by aslakhellesoy** [comment] 2015-06-17 20:07
I'm bitten by this as well - the highlight theme's background and foreground colours are overridden by theme.scss.

**Comment by borisschapira** [comment] 2015-06-17 20:11
@hakimel, any explanation ? I would gladly make a Pull Request but I imagine you've made it that way for a reason.

**Comment by shmerl** [comment] 2015-06-30 19:07
Looks like it's the same bug as I stumbled upon in #1290.

**Comment by demoneaux** [comment] 2016-03-06 09:41
Closing this as a duplicate of #1290 which has been fixed.

**Closed by demoneaux** 2016-03-06 09:41 UTC
