### ISSUE TITLE
Speaker view with local files without server

### ISSUE THREAD

**Issue by merkste** [hakimel/reveal.js#3158] opened 2022-03-18 10:04 UTC
I have a local presentation that I made with reveal.js 4.0.2 Speaker view was usable locally without setting up a server back then. After upgrading to the current release/master, it stopped working. The speaker view tells me that it cannot connect and to reload the presentation.
- I suppose this is a regression, isn't it?
- If not, what do I have to do to enable this feature again?
Speaker view with local files and without a server is especially important for me when presenting from a computer that is not under my control and no or a wonky internet connection.

**Comment by hakimel** [comment] 2022-03-18 10:09
Thanks for reporting. This is a regression and should be fixed. I want to continue to allow the speaker view to work without requiring a web server.

**Comment by merkste** [comment] 2022-03-18 12:47
Thanks for taking care of this issue and the need. =)

**Comment by lief-erickson** [comment] 2022-03-20 22:24
Additional info that may be helpful...

Speaker notes were working for me without a server using 4.2.1. With 4.3.0/master, speaker notes do work locally with Firefox but not with Chrome or Edge. As @merkste reported, they do work when using a server.

**Comment by hakimel** [comment] 2022-03-21 08:22
This has been fixed in 3077ddbd0933d2172db6790e35a50e1614efa8e9

Will publish a 4.3.1 release that includes the fix soon.

**Closed by hakimel** 2022-03-21 08:22 UTC

**Comment by merkste** [comment] 2022-03-21 15:24
That was fast. Thanks a lot. I'll give it a try asap.

**Comment by lief-erickson** [comment] 2022-03-21 15:29
Tested with 4.3.1/master and the fix works for me. 👍

**Comment by merkste** [comment] 2022-03-28 08:32
Nice, works for me too. Thanks!
