### ISSUE TITLE
Empty page after each slide when exporting PDF from 3.4.0

### ISSUE THREAD

**Issue by pkubowicz** [hakimel/reveal.js#1804] opened 2017-01-24 07:07 UTC
To reproduce:
1. clone reveal.js
2. run `npm install && npm start`
3. export to PDF according to https://github.com/hakimel/reveal.js#pdf-export

Result: you have 4 pages instead of 2. There is an empty page after each slide.

You can also change `index.html` to
```
Reveal.initialize({
			pdfMaxPagesPerSlide: 1,
```
but this does not have any effect. I tried using every bundled theme, but this also does not change the number of pages.

For me the vanilla presentation from the official repository should export correctly as PDF.

**Comment by hakimel** [comment] 2017-01-24 14:33
This should be fixed in master. Can you give it a try and let me know if it works for you as well?

Pretty major bug, so I'll put out a new release once the fix is confirmed.

**Comment by pkubowicz** [comment] 2017-01-24 15:31
I checked it also on my own presentation and the fix works fine. Thanks a lot!

**Comment by hakimel** [comment] 2017-01-25 09:49
Thanks for checking but turns out that change broke PDF exports through command line tools :/ Reworked it to avoid adjusting the page height and breakpoints.

**Comment by pkubowicz** [comment] 2017-02-09 06:51
@hakimel This issue is present again in master. Reproduces as before. See the `git bisect` log:
```
# bad: [1413cbc1a9344a6366c30fb0e83d5b6afc18f6d3] Merge pull request #1636 from traff/master
# good: [286b69b61f64bf47dd3ea710175aeb4de8288d9f] fix empty pages in pdf exports (closes #1804)
git bisect start 'HEAD' '286b69b61f64bf47dd3ea710175aeb4de8288d9f'
# bad: [9f8e4d5742df486cce577f6e0dbae666aabc4eb1] 3.4.1
git bisect bad 9f8e4d5742df486cce577f6e0dbae666aabc4eb1
# bad: [953d302f8b3c1a5dfc430f2e34b67a81bc35c9d2] adjust pdf margins instead of heights to fix #1804
git bisect bad 953d302f8b3c1a5dfc430f2e34b67a81bc35c9d2
# good: [d9dcff1503cb4e8043a2b434de3cc635914164cb] additional fix for empty pages in pdf exports #1804
git bisect good d9dcff1503cb4e8043a2b434de3cc635914164cb
# first bad commit: [953d302f8b3c1a5dfc430f2e34b67a81bc35c9d2] adjust pdf margins instead of heights to fix #1804
```

**Comment by hakimel** [comment] 2017-04-03 12:48
Reopening.

I'm seeing the empty pages appear when printing in Chrome 59, but not 57. Have been pursuing a fix for a while but haven't found one that works for both in-browser and CLI printing yet.

**Comment by hakimel** [comment] 2017-04-04 11:40
This should be fixed in a way that works for both in-browser and command line (phantom, wkpdf etc) printing now.

Give it a try when you get a chance.

+ @Skyr

**Comment by Skyr** [comment] 2017-04-04 20:14
Sorry, no luck - demo.html still results in 66 pages.
(tested with Chromium on Fedora 24 (56.0.2924.87))

**Comment by Skyr** [comment] 2017-04-05 09:25
My fault - I just checked the master.
The live demo is working perfectly :+1:

**Comment by hakimel** [comment] 2017-04-05 11:48
Whew, thanks!

**Closed** 2017-04-26 12:22 UTC

**Comment by nickjmeyer** [comment] 2017-08-06 18:33
I'm having this same issue, except it seems slightly different.  Instead of having a single blank page after each slide, the amount of blank space below each slide seems to be increasing exponentially.  I have a ~45 slide deck and using `?print-pdf` I get a ~46k page document.

I have yet to narrow down my html file to see what is causing it.  Will do this next weekend if no one has jumped on it before me.
