### ISSUE TITLE
fragment state not part of the hashtag url

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [hakimel/reveal.js#1125] opened 2015-02-09 09:40 UTC
this makes serving the presentation from a livereload using server a chore,
because every fragment-using page is returned to the initial state on reload

which in practice means many edits requires an action in the browser to see the result

**Comment by demoneaux** [comment] 2016-12-14 02:34
Duplicate of #228. See https://github.com/hakimel/reveal.js/pull/228#issuecomment-10261098.

**Closed by demoneaux** 2016-12-14 02:34 UTC
Labels: duplicate
