### ISSUE TITLE
Not working when opened in a jqueryui dialog

### ISSUE THREAD

**Issue by colingoldberg** [hakimel/reveal.js#1462] opened 2015-12-14 17:03 UTC
Hi,

I am trying to embed this in a web app, by opening it in a jquerui dialog. 
ie.
$.get('/getting_started/getting_started.reveal.html', function(gs_contents) {
    		document.getElementById("ritc-show-getting-started-dialog").innerHTML = gs_contents;
    		$( "#ritc-show-getting-started-dialog" ).dialog({
				width: 500,
				maxHeight: 600,
				position: { my: "right top", at: "right top", of: window },
				title: "Getting Started"
			});
		});
}

I have used your demo html contents (with most section contents removed). The contents are very briefly displayed - but background is not changed to black, and the display disappears immediately.

It works with my modifications when not in a dialog window. 

Not sure if this is a bug or my setup is not allowed. Please help.

Thanks

Colin Goldberg

**Comment by demoneaux** [comment] 2016-03-04 14:11
This seems like a request for #552, too allow embedding Reveal.js in a section of the page. Currently this isn’t possible, and you should use an `<iframe>` if you need to do so. Closing as a duplicate of #552.

**Closed by demoneaux** 2016-03-04 14:11 UTC
