### ISSUE TITLE
Overview Mode is broken when width is 100%

### ISSUE THREAD

**Issue by waywaaard** [hakimel/reveal.js#1247] opened 2015-06-02 12:40 UTC
When setting the ```width: "100%"``` the overview mode is not usable anymore. It does not shrink the individual slides.

You can try this on the official reveal-js demo when executing following snippet:

```javascript
Reveal.configure({width: "100%"});
```

**Comment by yarray** [comment] 2015-07-22 10:12
+1

**Comment by Jmuccigr** [comment] 2016-02-26 19:57
Biting me too, but I think the problem is  present for any percentage value.

**Comment by Jmuccigr** [comment] 2016-04-04 16:27
Any activity on this one? Really a pain.

**Comment by hackhowtofaq** [comment] 2016-04-05 10:45
Same problem here...

**Comment by hakimel** [comment] 2016-04-13 13:22
Just fixed this in the dev branch. Will be released with 3.3.0.

**Closed by hakimel** 2016-04-13 13:22 UTC
