### ISSUE TITLE
How to change slide background color for full presentation mode

### ISSUE THREAD

**Issue by tomjohnson1492** [hakimel/reveal.js#1386] opened 2015-10-06 14:35 UTC
When I have a theme configured (such as beige.css) and I press "F" to switch to full screen presentation mode, the slide background changes to black. How can I prevent the slide background color changing away from beige to black?

The only workaround I've found is to add a `data-background` property to each `section` element:

```
<section data-background="#f7f2d3">
```

Surely there's a master setting somewhere that controls the background color when the slides are in F mode, right?

**Comment by hakimel** [comment] 2015-10-06 18:27
This was a bug – the background in fullscreen mode should automatically match the theme.

Just added a fix for this and confirmed that it's working in Chrome OS X.

**Closed by hakimel** 2015-10-06 18:27 UTC

**Comment by tomjohnson1492** [comment] 2015-10-06 19:13
Awesome. Works great! Thanks for fixing it quickly.

**Comment by CyberShadow** [comment] 2016-05-02 12:19
@hakimel  This bug seems to be back in `master`. With a fresh checkout, replacing `black.css` in `index.html` with `white.css`, then going full-screen, causes the background to become black.

**Comment by kathrynwp** [comment] 2016-06-11 17:43
Hi @hakimel - like @CyberShadow, I'm getting a black background in full-screen mode in Firefox 47.0, even though the background is white (as it should be) when **not** in full-screen mode. 

This was **not** happening in Firefox 46.x.

Adding this fixes the issue, returning the full-screen background to white.

```
html { 
  background-color: #fff !important; 
}
```

The issue is not present in Chrome 51.0.2704.84 or Safari 9.1.1.

**Comment by ranr01** [comment] 2016-06-13 02:49
same here on firefox 47...

**Comment by apricis** [comment] 2016-06-13 12:24
same here for firefox 47.0
in dev console it gives the following warning: "Prefixed Fullscreen API is deprecated. Please use unprefixed API for fullscreen. For more help https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API"

**Comment by hakimel** [comment] 2016-06-20 08:30
Just pushed a fix for this to the dev branch so all theme backgrounds will display correctly in fullscreen mode. 

Fullscreen ancestor selectors were moved from core `reveal.scss` to the theme template `theme.scss`. Check out the commit for a full diff: b7e0d9b1c79a475249777d734a9675b1ba03a47a

**Comment by QHose** [comment] 2017-09-15 11:26
I have this issue again with a fresh pull...

**Comment by bnjmnt4n** [comment] 2018-01-22 07:52
Can't seem to replicate this anymore with latest Firefox 57.
