### ISSUE TITLE
Destroy Reveal

### ISSUE THREAD

**Issue by kayz1** [hakimel/reveal.js#1259] opened 2015-06-08 13:50 UTC
How can I destroy Reveal after the use?

Reveal.initialize(); // first initialization
... // usage
Reveal.destroy(); // clean up && reset internal state?

So I can use it again (show same or another presentation) without messing up the slides?

**Comment by waywaaard** [comment] 2015-06-19 17:51
That would be super helpful, when loading presentations dynamically.

**Comment by FeliciousX** [comment] 2015-07-22 04:03
:+1: We really need this feature! For now I just did the hackish way  and use `Reveal.removeEventListeners()` and `Reveal.addEventListeners()`

**Comment by waywaaard** [comment] 2015-07-22 05:20
Thanks for the tipp with the EventListeners. I noticed that this is not enough in my case. I try to dynamically reload the presentation and the layout gets messy.

After initializing I do this:
```js
      // rearrange layout
      Reveal.layout();

      try {
          Reveal.slide(0, 0, 0);
      } catch (ex) {
        // figure out why this happens sometimes
        console.log(ex);
      }
```

**Comment by mvgalle** [comment] 2016-06-23 19:50
Reveal is awesome, but it ends up breaking the scrolling functionality in my application. The WORKAROUND is really simple.... instead of opening the presentation in the same window/page, you should just pop it up in a new window. In your <a href... do the following: 

`<a href="linkToPresentation" target="_blank"`

Loading in a new window allows Reveal.js to manipulate the dom only for the window it opens in, and allows the rest of the app to run normally. 

#1145

**Comment by demoneaux** [comment] 2016-12-09 06:33
Closing as duplicate of #1145:

> There isn't, reveal.js makes lots of changes to the DOM so it would be difficult to roll all that back. Perhaps you could work around this by reloading the page and not initializing the framework.

**Closed by demoneaux** 2016-12-09 06:33 UTC

**Comment by akash-pal** [comment] 2018-03-22 16:28
Even reloading the page doesn't work, this issue needs to be reopened.

**Comment by MaximVanhove** [comment] 2018-03-27 13:04
@akash-pal I found out that this resets your presentation even if your dom has changed

```
Reveal.initialize()
Reveal.slide(-1, -1, -1)
Reveal.sync()
```

**Comment by akash-pal** [comment] 2018-03-29 09:54
@MaximVanhove thanks for your reply,
I actually commented out the below line:

  ```
   // Make sure we only initialize once
     // if( initialized === true ) return;

```
This enabled me to initialize again when I changed the page. 

I also had autoSlide on
     
       `Reveal.configure({ autoSlide: 4000 });`

So when I changed the page, I wrote a function to cancel the time and slide to the first slide. 
       
      ```
 cancelTimer: function(){
			pause();
			slide(0);
	}
```

I have then exposed the cancelTimer via the API.

This way I am able to use reveal in AngularJS

**Comment by MaximVanhove** [comment] 2018-03-29 10:00
Great that you got it working. I'm actually using this in Vue 😀

**Comment by PhamMinhKha** [comment] 2019-11-03 04:21
> @akash-pal I found out that this resets your presentation even if your dom has changed
> 
> ```
> Reveal.initialize()
> Reveal.slide(-1, -1, -1)
> Reveal.sync()
> ```

thank you. you save my day

**Comment by adavie1** [comment] 2021-08-22 03:51
> Great that you got it working. I'm actually using this in Vue grinning

Can you share how?

**Comment by vinaymavi** [comment] 2024-03-23 18:53
in Version `4.3.0` 

```
Reveal.distroy()
``
will work. 

https://revealjs.com/initialization/#destroy
