### ISSUE TITLE
Spaker mode and Chrome  dies with shrink fragment style

### ISSUE THREAD

**Issue by reagle** [hakimel/reveal.js#1191] opened 2015-04-02 17:49 UTC
When I'm on [this slide](http://lab.hakim.se/reveal-js/#/7/1) and stepping through the fragments with the speaker window open, Chrome 41.0.2272.118-1 dies when hitting the shrink example.

**Comment by hakimel** [comment] 2015-04-03 09:06
This is a duplicate of #1150

It's actually crashing because of the "roll-in" fragment that appears in the upcoming slide window.

**Closed by hakimel** 2015-04-03 09:06 UTC
