### ISSUE TITLE
?print-pdf removes links

### ISSUE THREAD

**Issue by davidaparicio** [hakimel/reveal.js#2583] opened 2020-02-12 18:23 UTC
I have the same issue #1078 (no links in PDF export) on MacOS

- Chromium Version 80.0.3960.0 (Developer Build) (64-bit)
- Firefox Version 73.0 (64-bit)

on Reveal.js presentations like [Reveal-hugo](https://themes.gohugo.io/theme/reveal-hugo/?print-pdf&showNotes=false&pdfSeparateFragments=false), and the [official website](https://revealjs.com/?print-pdf)

**Comment by pfisterer** [comment] 2020-02-14 18:18
I have the same issue. Links work neither inside the browser nor in the generated PDFs.

I've been able to reproduce this on MacOS (using the latest Chrome and Firefox browsers) and iOS using Safari.

**Comment by hakimel** [comment] 2020-03-10 09:36
@telliott22's fix in #2628 has been merged and is available in master.

I tried Chrome 80.0.3987.132 stable but was not able to reproduce this issue with exports. Links were not clickable when viewing the ?print-pdf page in the browser, but they worked after saving to PDF. Multiple people have reported this so I'm sure there's an issue that I'm not seeing, can you check if the updated print CSS fixes the problem? Thanks.

**Closed by hakimel** 2020-03-10 09:36 UTC

**Comment by pfisterer** [comment] 2020-03-11 16:21
Great, thanks a lot! Now it works (in the browser and the PDF).
