### ISSUE TITLE
Reveal.js highlighting is broken on slow internet connection and/or server being slow

### ISSUE THREAD

**Issue by Manvel** [hakimel/reveal.js#2162] opened 2018-05-18 15:23 UTC
## Background
I did notice this issue when I was preparing [current](https://cmints.io/en/presentation#/) presentation and experiencing slow response from my server. Anyway I have prepared actual reproduction steps with the default Reveal.js install below:

## Reproduction steps
- Clone [revealJS](https://github.com/hakimel/reveal.js) repository and run the server
- Replace Slide1 with content below:
```html
<section>
  <h3>Slide 1</h3>
  <pre><code>
  const date = new Date(2018, 10, 12);
  console.log(new Intl.DateTimeFormat('en-GB').format(date));
  console.log(new Intl.DateTimeFormat('en-US').format(date));
  console.log(new Intl.DateTimeFormat('lt-LT').format(date));
  </code></pre>
</section>
```
- Navigate to http://localhost:8000/ in Chrome Browser (Were using Chrome v66 on Mac)
- Open Chrome Dev Tools and from the Network tab select `Slow 3G preset ` 
- Clear the cache and reload the page
- Observe

### Observed Behavior

Highlight.js doesn't highligh `<pre><code>` blocks and current error is thrown in the console:

```
Uncaught ReferenceError: hljs is not defined
    at callback ((index):52)
    at reveal.js:423
    at f (head.min.js:6)
    at Array.<anonymous> (head.min.js:6)
    at u (head.min.js:6)
    at head.min.js:6
    at e (head.min.js:6)
    at head.min.js:6
```

### Expected behavior
No error is thrown and code is highlighted after the highlight.js is downloaded.

## Notes:
- I did notice that reveal.js using some version of highligh.js which is almost 500kb(I assume because it contains all languages). The suggested cdnjs version(with common languages) in https://highlightjs.org/download/ is less than 5kb.
- Even though I think this issue is connected with how Reveal.js is dealing with the dependency scripts updating the library might be a good start for fixing this issue.

**Comment by Manvel** [comment] 2018-05-18 16:16
- I just created a [pull request](https://github.com/hakimel/reveal.js/pull/2163) to replace big highligh.js file, this fix will also resolve the reproduction steps in current issue, but I still think that it make sense to check why Reveal.js couldn't handle this in the [dependencies loading implementation](https://github.com/hakimel/reveal.js/blob/master/index.html#L40) (I still think this issue might strike back after again)
- Also do you know, why the old version of the highlightJS was so big ?
  - Did it include more languages ?

**Comment by Manvel** [comment] 2018-05-18 18:21
Basically seems like current version, contains all languages, that's why it's so big.

**Comment by Manvel** [comment] 2018-05-18 18:38
I've updated the description, as seems like current bundled version of highlight.js contains all languages, while the pull request only has Common Languages bundled, ideally there would be an option to load all languages, as I would assume Common Languages should make most of the users happy. So I'll keep the Pull Request until I've got a comment about what you think will be the best solution.

**Comment by flashpixx** [comment] 2018-09-18 21:09
I could reproduce the problem, but I could fix it and I can use hightligh.js 9.12.
I take reveal.js from the CDN service, so it is the raw component. Than I add also from the CDN hightlight.js as [dependency and load all language components manually](https://github.com/Informatikwerkstatt/informatikwerkstatt.github.io/blob/master/_layouts/slide.html#L55) inside the callback
I add also the highlight.js CSS theme content to the reveal.js theme [css file](https://github.com/Informatikwerkstatt/informatikwerkstatt.github.io/blob/master/assets/layout.css#L415). With this solution I get a stable working result, [see example](https://informatikwerkstatt.github.io/threads-activities-intent/#/2/1)

**Comment by hakimel** [comment] 2018-09-19 08:15
Thanks for the clear instructions on how to reproduce this.

I've debugged it and it's failing because head.js has a built-in timeout before it gives up on loading a script. From looking at the source, I think that value is hardcoded at 7s. Haven't found a way to work around/override the timeout but will keep looking.

**Comment by flashpixx** [comment] 2018-09-19 08:28
Is it possible to remove Highlight.js as plugin? With my solution you don‘t need the plugin structure. I cannot figure out why you put a short JS Code in the hightlight.js file. I think a wrapper around my solution should be a more clean solution. 
For the CSS Integration the problem seems to be that the Reveal.js loads the style by the id first, so the Highlight.js CSS is overwritten by the Reveal.js CSS

**Comment by hakimel** [comment] 2018-10-04 12:52
I just pushed a fix for this to the dev branch. As of next version–assuming all goes well in testing–we'll drop the head.js dependency in favor of a simplified built-in script loader. This new loader fixes the issue when loading scripts on slow connections. Please do give it a shot if you get a chance :)

No plans for dropping highlight.js from the repo right now but thanks for the suggestion.

**Closed by hakimel** 2018-10-04 12:52 UTC

**Comment by flashpixx** [comment] 2018-10-04 18:53
On my perspective it can be interested for users to use a special version of a library, so if you build hightlight.js inside Reveal.js the version is strict fix. If I need for my use-case another version of a dependency I just build this in a dynamic way like my solution. So in general to the flexibility of use-cases my suggestion is to remove the strict dependencies to a more flexible solution, so that I can decide as user of Reveal.js which version I would like to use
