### ISSUE TITLE
inline scripts and styles

### ISSUE THREAD

**Issue by rusimody** [hakimel/reveal.js#1335] opened 2015-08-23 00:41 UTC
When one needs to mail a presentation to someone it would help if it could be a single file.
So is it possible to inline the scripts and stylesheets?

**Comment by demoneaux** [comment] 2016-03-08 11:09
It’s possible, although for now you might have to do it manually. I’ll close this as a duplicate of #788.

**Closed by demoneaux** 2016-03-08 11:09 UTC
