### ISSUE TITLE
Jump to begin after scroll

### ISSUE THREAD

**Issue by rgom** [hakimel/reveal.js#1932] opened 2017-06-29 19:50 UTC
Hi all,
I'm not sure if this is a bug or feature, but I couldn't find an answer after extensive web search.

I'm creating a presentation about some Python library. It's done from Jupyter notebook, converted then to slides with reveal.js.

The problem I have is that some code examples generate output which is longer than screen (vertical).
I can see vertical scrollbar and can use it to scroll down, but during (!) and after scrolling (some delay) the slides automatically jump to the begin (vertical top of the same slide).

How can I disable that? I've found some links (https://github.com/hakimel/reveal.js/issues/118, https://stackoverflow.com/questions/20078932/reveal-js-unable-to-scroll-in-the-slides, ...) but none provided an answer.

I have bleeding edge version (master from two days ago) of reveal.js.

TIA,
Robert

**Comment by nicorneau** [comment] 2017-10-20 12:09
Hi,
I'm having the same problem in the same context. Any idea?

Nicolas

**Comment by paugier** [comment] 2017-11-27 09:48
Hi, 
I encounter the same problem, which is indeed very annoying.

I found the following workaround to be able to scroll down:
- use reveal.js version 3.2
- no youtube video with iframe

Hoping it could give clues about how to really solve this problem.

**Comment by alixdamman** [comment] 2018-01-29 09:08
Hi,
I'm having the same problem in the same context but only when using Windows. 
Not with Linux/Ubuntu?

Alix

**Comment by bnjmnt4n** [comment] 2018-02-01 12:00
Hi, could you create a reproduction case for us to look at?

**Comment by alixdamman** [comment] 2018-02-01 22:34
In my case, clone my github repository https://github.com/alixdamman/memento.git 
Then go to directory /python and run:
> jupyter nbconvert functions_for_dummies.ipynb --to slides --template slides_reveal.tpl --post serve

Works fine on Kubuntu 17.10 with both Chrome and Firefox. 
Jumps to begin after scroll on Windows 10 with both Chrome and Firefox.

Used reveal version is 3.1.0

**Comment by bnjmnt4n** [comment] 2018-02-08 13:07
Hi, sadly I don't have python on my computer due to administrative restrictions. Is it possible for you to try switching to the latest Reveal version (3.6.0), and upload a copy of the live slides online for us to look at?

**Comment by alixdamman** [comment] 2018-02-16 16:54
@bnjmnt4n I updated my jupyter package which now use version 3.5.0 of Reveal by default. This solved the problem. As mentioned by paugier above, the problem seemed to be linked to versions <3.2 of Reveal

**Comment by bnjmnt4n** [comment] 2018-02-19 03:49
Closing this for now then, since it's a big in an old version of Reveal.

**Closed by bnjmnt4n** 2018-02-19 03:49 UTC
Labels: invalid
