### ISSUE TITLE
Transition does not work in Firefox 48.0.2

### ISSUE THREAD

**Issue by kovacsv** [hakimel/reveal.js#1684] opened 2016-09-04 12:00 UTC
Browser: Firefox 48.0.2, Windows
Reveal.js: latest

After a Firefox update the transition stopped working. The previous slide disappears, but the next one does not appear. If you refresh the page it appears correctly. It worked before the Firefox update, and it seems it occurs only if there are vertical slides.

Repro: http://kovacsv.hu/other/reveal/error.html, press the right arrow: the slide does not appear.

Thanks,
Viktor

**Comment by kovacsv** [comment] 2016-09-04 16:42
Some more info: The above error appears if the transition if convex. With default transition the slide appears, but the animation is still missing. The issue also appears with vertical slides here: http://lab.hakim.se/reveal-js

**Comment by rajgoel** [comment] 2016-09-10 15:45
Looks like this is related to #1627

**Comment by hakimel** [comment] 2016-10-05 12:04
Closing this as a duplicate of #1627

**Closed by hakimel** 2016-10-05 12:04 UTC
