### ISSUE TITLE
Cloudflare's CDN appears to be missing the CSS files for RevealJS since version 4.0

### ISSUE THREAD

**Issue by SylvainCorlay** [hakimel/reveal.js#2722] opened 2020-07-07 10:56 UTC
https://cdnjs.com/libraries/reveal.js/4.0.2

**Comment by bnjmnt4n** [comment] 2020-07-07 11:14
Duplicate of #2712. The CSS folders should be included in the next release.

**Closed by bnjmnt4n** 2020-07-07 11:14 UTC

**Comment by SylvainCorlay** [comment] 2020-07-07 11:29
Unlike reported in #2712 it is not just about the theme, but also the base reveal.css, so that the CDN-distributed version of reveal.js is not functional.

Also, the directory structure of `https://unpkg.com/browse/reveal.js@4.0.2/dist/` does not match that of cloudflare and lacks the minified files.

**Comment by hakimel** [comment] 2020-07-07 16:46
Not sure what’s happened to that cdnjs distribution. Looks like the /dist directory is missing?

The distribution on unpkg has all of the correct files. It doesn’t lack the minified files, /dist/reveal.js and /dist/reveal.css are both minified.

**Comment by SylvainCorlay** [comment] 2020-07-07 16:48
> The distribution on unpkg has all of the correct files. It doesn’t lack the minified files, /dist/reveal.js and /dist/reveal.css are both minified.

Correct, although the file name does not include 'min' unlike on cloudflare.

**Comment by bnjmnt4n** [comment] 2020-07-07 16:48
CDNJS uses this configuration (https://github.com/cdnjs/packages/blob/master/packages/r/reveal.js.json) to update its library on any git tag changes. I believe the `dist` library wasn't present in previous versions and isn't covered by this whitelist: https://github.com/cdnjs/packages/blob/e40a5056637aebc8776555c5d2879c402d507e1d/packages/r/reveal.js.json#L18-L27. A simple PR should fix this and include the proper files on the next version bump.

**Comment by hakimel** [comment] 2020-07-07 17:11
That explains it, thanks @bnjmnt4n! I’ll submit a PR to update the directory list and project info ahead of the next version.

**Comment by hakimel** [comment] 2020-07-08 08:12
Opened PR @ https://github.com/cdnjs/packages/pull/335
