### ISSUE TITLE
Full setup with nodejs 12 fails

### ISSUE THREAD

**Issue by Seth-Gecko** [hakimel/reveal.js#2473] opened 2019-09-02 14:13 UTC
I'm on Debian Stretch. When installing the full setup, the build currently fails. Not sure if this is an issue with reveal.js.

[Relevant log](https://del.dog/izosojimog.rb)

For now, I have switched to nodejs 11 and everything works as expected.

**Comment by xjackk** [comment] 2019-09-02 23:23
can confirm i am getting this exact build error on node 12 as well.

**Comment by edgranau** [comment] 2019-09-10 02:37
I had a similar issue:

```
2 warnings and 5 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/edwin/Workspace/Edwin/Code/reveal.js/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.10.0/bin/node" "/Users/edwin/Workspace/Edwin/Code/reveal.js/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/edwin/Workspace/Edwin/Code/reveal.js/node_modules/node-sass
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/edwin/.npm/_logs/2019-09-10T02_04_38_001Z-debug.log
```

It looks like the problem is actually with the node-sass version. see [here](https://github.com/sass/node-sass#supported-nodejs-versions-vary-by-release-please-consult-the-releases-page-below-is-a-quick-guide-for-minimum-support)

## Fix for Nodejs v12.10.0

- update `node-sass` to version `^4.12.0` in your `package.json`
- `npm install`
- `npm audit fix`

Cheers

**Comment by hakimel** [comment] 2020-01-11 19:33
This has been fixed in master now by upgrading to node-sass 4.13.0. Thanks for tracking down the issue, @edgranau!

**Closed by hakimel** 2020-01-11 19:33 UTC

**Comment by GreenRidingHood** [comment] 2020-04-21 16:33
downgraded node@10
