### ISSUE TITLE
Short review with a bug report

### ISSUE THREAD

**Issue by ch2capg** [hakimel/reveal.js#1776] opened 2016-12-16 19:52 UTC
Dear hakimel,

I have used reveal.js for presentation and want to quickly give a feedback.

Pros
--------------------------------------------------

- Works well on firefox.
- Basic functionality of speaker notes works.
- Readme file instructions are essentially clear:
    + Setup with LaTeX works.
    + Setup with note.js works.
- Creating slides with Markdown saves a lot of time.

Cons
--------------------------------------------------

- `<h1>` is too big.
- It was not possible for me to change the behavior of `<li>` in `<ul>` without
  any class attribute.
- Compared to LaTeX beamer.sty I miss the following layout features:
    + Title cannot be displayed on the top left corner.
    + I cannot manipulate the bottom line of my slides.
    + I can use 'c/t' to get current page / total page put I cannot change its
      size or position.
- External Markdown did not work with node.js.
- I found two bugs in speaker notes:
    + Links do not work.
    + Videos are not synchronized.
  The latter point is potentially dangerous if you are not aware of it.
- The PDF output has at least two bugs:
    + 'c/t' has a weird output.
    + If I change width and height then the output looks strange.
    + The first slide has to small margin on the top.

Thank you for sharing this piece of code!  My presentation looked very good with reveal.js.

**Comment by demoneaux** [comment] 2017-05-03 09:39
Thanks for the report! A lot of the issues you mentioned can be fixed with CSS by designing your own theme/styles. We'll also look into your other points. Closing this for now :)

**Closed by demoneaux** 2017-05-03 09:39 UTC
