### ISSUE TITLE
Slide Notes timer doesn't work

### ISSUE THREAD

**Issue by vvug** [hakimel/reveal.js#1922] opened 2017-06-17 13:58 UTC
When I open the Slide Notes browser page (pressing `s`) the timer doesn't start. I'm using Chromium and I'm getting this error in the console

```
Uncaught ReferenceError: Reveal is not defined
    at getTimings (notes.html:484)
    at setupTimer (notes.html:541)
    at handleConnectMessage (notes.html:387)
    at notes.html:354
```

this doesn't happen in the standard view. I'm using the latest git version with Chromium 59. I'm initializing the presentation like this:

```
    <script src="../reveal.js/lib/js/head.min.js"></script>
    <script src="../reveal.js/js/reveal.js"></script>
    <script>
      Reveal.initialize({
          dependencies: [
            // Interpret Markdown in <section> elements
            { src: '../reveal.js/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
            { src: '../reveal.js/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
            { src: '../reveal.js/plugin/notes/notes.js', async: true }
          ],
          slideNumber: false
      });
    </script>
```

**Comment by srushe** [comment] 2017-06-19 09:29
I'm seeing the same issue. This bug appears to have crept in in [commit 715cf0b](https://github.com/hakimel/reveal.js/commit/715cf0ba11db0f913cfd2edb56a2c66aed57b505).

**Comment by vvug** [comment] 2017-06-20 07:45
To me it *does* happen the first time I press `s`.

**Comment by aaroncampbell** [comment] 2017-07-10 22:05
It happened for me the first time I pressed `s` as well. Using incognito mode fixed it for me, so I think it was some kind of caching issue (I had upgraded from a previous release). Killing all cache didn't seem to help, but restarting Chrome did.

**Comment by seanho00** [comment] 2017-08-17 06:15
I'm pulling Reveal from a CDN and have run into this issue as of 3.5.0, due to a CORS issue for the slide timing stuff.

Because `notes.html` is on the CDN and the main presentation is on a different domain, [notes.js:25](https://github.com/hakimel/reveal.js/blob/3.5.0/plugin/notes/notes.js#L25) fails, and the pop-up never gets a reference to the main window's Reveal object.

Would it be possible to use the existing message-passing `postMessage()` channel between the two windows to send the slide timing data, so that the Reveal object doesn't need to be shared between the two windows?

This issue doesn't appear when `notes.html` is on the same domain as the main presentation.

**Comment by kuncevic** [comment] 2017-09-30 23:19
If I just `git clone https://github.com/hakimel/reveal.js` and then run `demo.html`  pressing `s` timer just won't start and in console windows what I can see is `Uncaught ReferenceError: Reveal is not defined`

**Comment by seanho00** [comment] 2017-10-01 02:07
@kuncevic, are you opening `demo.html` directly in the browser (`file:///` URL), or running a local web server? 

As per [the documentation on speaker notes](https://github.com/hakimel/reveal.js/blob/master/README.md#speaker-notes), notes only work from a web server.

**Comment by kuncevic** [comment] 2017-10-01 03:36
@seanho00 i c, thanks for pointing that out. I was using a `file:///`

**Comment by sbegueria** [comment] 2017-12-04 14:45
I'm having the same issue: timer not working when pressing 's', either on Chrome and Safari.

**Comment by lechten** [comment] 2017-12-04 14:54
For me the following works with Firefox (for presentations served from a web server as well as with local files): 
1. Press "s"
2. Allow pop-ups. The speaker view window opens, timers stay at 0.
3. Close the pop-up window
4. Press "s" again. The speaker view window opens, timers advance.

**Comment by sbegueria** [comment] 2017-12-04 15:21
You're right, I got the same behavior on Firefox (for Mac). I could not replicated on either Safari or Chrome, though (timer is not working even the second time I open the window).

**Comment by bnjmnt4n** [comment] 2018-02-01 12:32
Closing since this isn't an issue as notes are meant to be run from a server for `postMessage` to work properly.

**Closed by bnjmnt4n** 2018-02-01 12:32 UTC
Labels: invalid

**Comment by DV-JF** [comment] 2018-09-13 11:40
> Took a while but I found out how to reproduce that error. It happens when you press the 'S' to open the speaker view, and then go back to the main window and press the 'S' key again while the popup is still open in the background.
> 
> It's not happening when first opening the speaker view in any browser that I've tested.
> 
> Wasn't able to find a way to fix it yet though.

@bnjmnt4n  @hakimel 

This bug is still present. I reproduce it e.g. on https://revealjs.com/ You may reconsider to open this issue again.

**Comment by hakimel** [comment] 2018-09-18 07:39
I tested revealjs.com again in Chrome canary/stable but the timer is working every time, except for the issue with pressing S while notes are already opened that I described above. 

#2104 looks like a good improvement to make the notes work locally.

I've moved the timer bug when opening notes twice to a new issue #2229

**Comment by mshagirov** [comment] 2018-10-04 14:50
I had the same issue, the timer didn't work for safari and chrome (whichever way I press "s").

Following the "full setup" from https://github.com/hakimel/reveal.js/ solved the issue.
