### ISSUE TITLE
Speaker View: Upcoming slide not updated

### ISSUE THREAD

**Issue by ratnanil** [hakimel/reveal.js#3285] opened 2022-09-26 05:59 UTC
I'm having some major issues with the Speaker View feature in revealjs. 

1. Changing the slides in the *Main* Window has no effect on the *Speaker View* Window
2. The *Upcoming Slide* is not updated

Here's a gif how the slides behave in my browser (first I activated the *Main* window, then the *Speaker View* Window. I've tested this on Firefox `105.0 (64-bit)` and Chrome `Version 105.0.5195.125 (Official Build) (64-bit)`. Is this a bug?

![output3](https://user-images.githubusercontent.com/12532091/192207694-bab90532-307b-492c-999d-890f92f71595.gif)

**Comment by ratnanil** [comment] 2022-09-26 06:49
Current workaround is using https://github.com/reveal/notes-server

**Comment by hakimel** [comment] 2022-09-26 06:55
I tried this in Firefox 105.0.1 / Chrome 105 on a Mac but the speaker view is syncing in both directions for me. Tested against your example (https://www.ratnaweera.xyz/revealjs-test/) and [revealjs.com/demo](https://revealjs.com/demo).

Anyone else that can give this a try on another platform?

**Comment by DLND8** [comment] 2022-09-26 09:30
I tried this on Windows in Chrome and I am also having the same issue.
I have `Windows 10` and Chrome `Version 105.0.5195.127 (64-Bit)` 

![image](https://user-images.githubusercontent.com/18243911/192242021-6b190f83-8bdb-4df7-91a9-cd970798ae07.png)

**Comment by hannorahn** [comment] 2022-09-26 12:00
I tried this on Windows in Chrome and I am also having the same issue.
I have Windows 10 and Chrome Version Version 105.0.5195.102

**Comment by ratnanil** [comment] 2022-09-27 10:09
I had asked two colleagues to test [revealjs.com/demo](https://revealjs.com/demo) on their windows setup (https://github.com/hakimel/reveal.js/issues/3285#issuecomment-1257925118 and https://github.com/hakimel/reveal.js/issues/3285#issuecomment-1257757051). Yesterday, I tested it on a friend's MacBook: We experience the same issue everywhere. I find this really really strange.. can anybody else test?

**Comment by 2e0byo** [comment] 2022-09-28 12:08
Curiously I find the upcoming slide updates *sometimes*.

**Comment by 2e0byo** [comment] 2022-09-28 12:17
Git bisect show the first bad commit is 62a85d55f8820c93dd2e60e34600b6eded8f7726.

@ratnanil @hannorahn @DLND8 can you confirm this doesn't happen before that commit?

**Comment by ratnanil** [comment] 2022-09-29 19:46
Hey @2e0byo: Thanks for digging into this! If I revert to commit f9ce61e, everything seems to work fine. I will check with @hannorahn on Monday, @DLND8, can you test if the speaker's view (hit <kbd>S</kbd> and allow popups) works for you here https://ratnanil.github.io/evealjs-test2?

**Comment by DLND8** [comment] 2022-10-04 08:11
@ratnanil Yes it works for me.

**Comment by 2e0byo** [comment] 2022-10-04 08:38
Unfortunately now I look at it that commit is just adding the minified/compiled output from some js elsewhere.  I'll try to have a look into this this weekend, but if anyone's got some experience developing this, they might want to do a proper bisect, going through the changes on the *source* for that minified file and compiling every time and find out what change actually caused the problem.

Incidentally I guess we should just use a tagged release for production anyway.  [Or in my case a CDN, because I'm lazy.]

**Comment by mbotsch** [comment] 2022-10-16 18:32
I can confirm that [revealjs.com/demo](https://revealjs.com/demo) does not work on current MacOS using either Firefox, Chrome, or Safari. It prints an error on the console due not not being able to call `getAttribute` on some undefined variable.

**Comment by ratnanil** [comment] 2022-10-17 04:56
Are you specifically talking about the speaker view?

I never noticed the console log warnings, but I get them too:

``` 
main.js:69 Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at HTMLDivElement.i (main.js:69:71526)
    at Object.Ie [as dispatchEvent] (main.js:59:70829)
    at I.goto (main.js:59:30243)
    at I.next (main.js:59:30523)
    at Object.Ot (main.js:59:84391)
    at L.onNavigateRightClicked (main.js:59:46383)

main.js:69 Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at HTMLDivElement.i (main.js:69:71526)
    at Object.Ie [as dispatchEvent] (main.js:59:70829)
    at I.goto (main.js:59:30243)
    at I.next (main.js:59:30523)
    at Object.Dt (main.js:59:84637)
    at L.onNavigateDownClicked (main.js:59:46558)
```

**Comment by hakimel** [comment] 2022-10-17 07:58
The `getAttribute` exception has been fixed and released in reveal.js 4.4.0: https://github.com/hakimel/reveal.js/releases

Please give it another try and let me know if you still have any issues with the speaker view not syncing. The website has been updated so you can test on [revealjs.com/demo](https://revealjs.com/demo). You can make sure you're testing the latest version by running `Reveal.VERSION` in the console.

**Closed by hakimel** 2022-10-17 07:58 UTC

**Comment by ratnanil** [comment] 2022-10-17 11:21
I can confirm that [revealjs.com/demo](https://revealjs.com/demo) works on my system. Thank you for this fix!

**Comment by mbotsch** [comment] 2022-10-17 11:23
Also works for me. Thanks a lot!
