### ISSUE TITLE
Section `id` with special characters

### ISSUE THREAD

**Issue by Peque** [hakimel/reveal.js#1346] opened 2015-09-05 20:38 UTC
Currently, if a section `id` has special characters (i.e.: é, à, ü, ø...) then:
1. The special characters are not displayed in the URL bar. Why?
2. If you execute `grunt serve` and modify the HTML file while displaying that section in the browser, it will automatically jump to the first slide, instead of displaying the same slide after the edit. Is not this a bug?

Content example:

``` html
  <div class="reveal">
    <div class="slides">

<section id="ascii-text">
  <h1>ASCII text</h1>
</section>
<section id="ømq">
  <h1>ØMQ</h1>
</section>

    </div>
  </div>
```

**Comment by schauder** [comment] 2016-08-01 13:25
At least when an id starts with a digit this will break the navigation. The second slide will be skipped in the following presentation when navigating with the space bar:

        <section>
            <section id="one"><h2>shows</h2></section>
            <section id="2-two"><h2>Gets skipped</h2></section>
        </section>
        <section>
            <section id="three"><h2>Shows to early</h2></section>
        </section>

While this is probably the same issue, it makes it much more grave, since it breaks pretty normal presentations

**Comment by schauder** [comment] 2016-08-01 13:27
This might be related to #1230

**Comment by bnjmnt4n** [comment] 2018-02-14 07:04
Closing this as a duplicate of #1230.

**Closed by bnjmnt4n** 2018-02-14 07:04 UTC
