### ISSUE TITLE
Feature request: vertical presentations

### ISSUE THREAD

**Issue by murvoy** [hakimel/reveal.js#1338] opened 2015-08-26 14:58 UTC
Dear developers,

I am currently using your library to set-up web-slides. Congrats for the very good job you did!
However, I am in a situation where having slides organized vertically makes more sense.

I realize there are vertical slides with sub-slides, but however, this means that the main progression is horizontal, and the sub-progression is vertical.

Would it be possible for you to add an option that, once set, organizes the presentation as follows:
- slides (<section>) are organized vertically (vertical transition),
- sub-slides (nested <section>) are organized horizontally (horizontal transition).

Thanks in advance, and keep up the good work!

Best,
Matthieu Urvoy

**Comment by waywaaard** [comment] 2015-08-26 16:07
This requires a lot of style and logic changes. See possible dupe: #602

**Comment by murvoy** [comment] 2015-08-26 16:23
Ok, thanks for the reply and the explanation!
I will make do with this then.

Best,
Matthieu

**Comment by demoneaux** [comment] 2016-03-06 09:35
Closing this as a duplicate of #602.

**Closed by demoneaux** 2016-03-06 09:35 UTC
